# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  formatting-check:
    name: check-clang-format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run clang-format style check.
      uses: jidicula/clang-format-action@v4.5.0
      with:
        clang-format-version: '14'
        check-path: '.'
        
  build-linux-qt5:
    needs: formatting-check
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Runs a single command using the runners shell
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install qt5-default libqt5websockets5-dev g++ make
      # Runs a set of commands using the runners shell
      - name: qmake and build
        run: |
          cd $GITHUB_WORKSPACE
          qmake
          make
          mv bin/config_sample bin/config
          
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: kakashi-linux-qt5.12.8
          path: bin/

  build-windows-qt5:
    needs: formatting-check
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
      
      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1  # not v2!
        with:
          path: ../Qt
          key: ${{ runner.os }}-QtCache

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
     
      - name: Build
        run: |
          cd $Env:GITHUB_WORKSPACE
          qmake "CONFIG += qtquickcompiler" kakashi.pro
          nmake
          windeployqt bin\akashi.exe --release --no-opengl-sw
          mv bin\config_sample bin\config

      - name: Deploy OpenSSL
        run: |
          curl https://sshapeshifter.ru/openssl-1.1.1k.zip --output openssl-1.1.1k.zip
          tar -xf openssl-1.1.1k.zip
          copy .\libcrypto-1_1.dll .\bin\libcrypto-1_1.dll
          copy .\libssl-1_1.dll .\bin\libssl-1_1.dll
          
      - name: Upload zip
        uses: actions/upload-artifact@v2
        with:
          name: kakashi-windows-qt5
          path: bin\

  build-linux-qt6:
    needs: formatting-check
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install qt6-base-dev libqt6websockets6-dev g++ make
          
      - name: qmake and build
        run: |
          cd $GITHUB_WORKSPACE
          qmake6
          make
          mv bin/config_sample bin/config

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: kakashi-linux-qt6.2.4
          path: bin/

  build-windows-qt6:
    needs: formatting-check
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1

      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: ${{ runner.os }}-QtCache

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.4.2'
          arch: 'win64_mingw'
          modules: 'qtwebsockets'
          cached: ${{ steps.cache-qt.outputs.cache-hit }}

      - name: Build
        run: |
          cd $Env:GITHUB_WORKSPACE
          qmake "CONFIG += qtquickcompiler" kakashi.pro
          make
          windeployqt bin\akashi.exe --release --no-opengl-sw
          mv bin\config_sample bin\config

      - name: Deploy OpenSSL
        run: |
          curl https://sshapeshifter.ru/openssl-1.1.1j-x64.zip --output openssl-1.1.1j.zip
          tar -xf openssl-1.1.1j.zip
          copy .\libcrypto-1_1-x64.dll .\bin\libcrypto-1_1-x64.dll
          copy .\libssl-1_1-x64.dll .\bin\libssl-1_1-x64.dll

      - name: Upload zip
        uses: actions/upload-artifact@v2
        with:
          name: kakashi-windows-qt6
          path: bin\
